
name: RosBP CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Install stuff
        run: |
           cd functions
           npm install
           cd .. 
      - name: Build
        run: npm run-script build
      - name: Firebase Deploy
        uses: w9jds/firebase-action@master
        with: 
          args: deploy --except functions
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
